node{
    agent any

    stages {
        stage('Build') {
            steps {
                echo "Build"
            }
          }
       stage('Test') {
            steps {
                echo "Test App"
            }
        }
        stage('Deploy') {
            steps {
                echo "Helloworld"
                }
        }
       
        }
    }
