node{
    agent any

    stages {
        stage('Build') {
            steps {
                
            }
          }
       stage('Test') {
            steps {
                echo 'Test App'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Helloworld'
            }
        }
       
        }
    }
